use_frameworks!

target 'xxx_Example' do
  pod 'xxx', :path => '../'

  target 'xxx_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
